const e5s = {
    'E25':{
        web3:['https://etc.etcdesktop.com', 'https://etc.rivet.link', 'https://0xrpc.io/etc'],
        token:'ETC',
    },
    'E45':{
        web3:['https://avalanche.drpc.org'],
        token:'AVAX',
    },
    'E55':{
        web3:['https://1rpc.io/celo', 'https://forno.celo.org'],
        token:'CELO',
    },
    'E65':{
        web3:['https://rpc.au.cc/flare'],
        token:'FLR',
    },
    'E75':{
        web3:['https://rpc.gnosischain.com'],
        token:'XDAI',
    },
    'E85':{
        web3:['https://rpc.fuse.io'],
        token:'FUSE',
    },
    'E115':{
        web3:['https://xdc.public-rpc.com'],
        token:'XDC',
    },
    'E125':{
        web3:['https://polygon-bor-rpc.publicnode.com'],
        token:'POL',
    },
    'E135':{
        web3:['https://bsc-rpc.publicnode.com'],
        token:'BNB',
    },
    'E145':{
        web3:['https://evm-rpc.sei-apis.com'],
        token:'SEI',
    },
    'E155':{
        web3:['https://rpc.berachain.com/'],
        token:'BERA',
    },
    'E165':{
        web3:['https://viction.drpc.org'],
        token:'VIC',
    },
    'E175':{
        web3:['https://rpc.plasma.to'],
        token:'XPL',
    },
    'E185':{
        web3:['https://ethereum-rpc.publicnode.com'],
        token:'ETH',
    },
    'E195':{
        web3:['https://optimism-rpc.publicnode.com'],
        token:'OETH',
    },
    'E205':{
        web3:['https://base-rpc.publicnode.com'],
        token:'BETH',
    },
    'E215':{
        web3:['https://arbitrum-one-rpc.publicnode.com'],
        token:'AETH',
    },
    'E225':{
        web3:['https://evm.astar.network', 'https://astar.api.onfinality.io/public'],
        token:'ASTR',
    },
    'E235':{
        web3:['https://cronos-evm.publicnode.com'],
        token:'CRO',
    },
    'E245':{
        web3:['https://evm.kava.io'],
        token:'KAVA',
    },
    'E255':{
        web3:['https://neon-proxy-mainnet.solana.p2p.org'],
        token:'NEON',
    },
    'E305':{
        web3:['https://api.harmony.one'],
        token:'ONE',
    },
    'E345':{
        web3:['https://node1.ozonechain.io'],
        token:'OZO',
    },
    'E365':{
        web3:['https://rpc.rei.network'],
        token:'REI',
    },
    'E385':{
        web3:['https://rpc.mantle.xyz'],
        token:'MNT',
    },
    'E395':{
        web3:['https://rpc.pulsechain.com'],
        token:'PLS',
    },
    'E405':{
        web3:['https://canto.gravitychain.io'],
        token:'CANTO',
    },
    'E425':{
        web3:['https://babel-api.mainnet.iotex.io'],
        token:'IOTX',
    },
    'E435':{
        web3:['https://rpc.au.cc/songbird'],
        token:'SGB',
    },
    'E445':{
        web3:['https://ultron-rpc.net'],
        token:'ULX',
    },
    'E455':{
        web3:['https://rpc.coinex.net'],
        token:'CET',
    },
    'E465':{
        web3:['https://eth-rpc-api.thetatoken.org/rpc'],
        token:'TFUEL',
    },
    'E485':{
        web3:['https://rpc.energyweb.org'],
        token:'EWT',
    },
    'E515':{
        web3:['https://tenet-evm.publicnode.com'],
        token:'TENET',
    },
    'E525':{
        web3:['https://pyrus2.ubiqscan.io'],
        token:'UBQ',
    },
    'E535':{
        web3:['https://rpc.gochain.io'],
        token:'GO',
    },
    'E545':{
        web3:['https://mainapi.omaxray.com'],
        token:'OMAX',
    },
    'E555':{
        web3:['https://api.wemix.com'],
        token:'WEMIX',
    },
    'E565':{
        web3:['https://evm.confluxrpc.com'],
        token:'CFX',
    },
    'E575':{
        web3:['https://1rpc.io/telos/evm'],
        token:'TLOS',
    },
    'E585':{
        web3:['https://mycrypto.rsk.co'],
        token:'RSK',
    },
    'E595':{
        web3:['https://api.metadium.com/prod'],
        token:'META',
    },
    'E655':{
        web3:['https://eth-rpc-karura.aca-api.network'],
        token:'KAR',
    },
    'E665':{
        web3:['https://eth-rpc-acala.aca-api.network'],
        token:'ACA',
    },
    'E705':{
        web3:['https://seed.omchain.io'],
        token:'OMC',
    },
    'E715':{
        web3:['https://rpc.omplatform.com'],
        token:'OM',
    },
    'E725':{
        web3:['https://node1.mintme.com'],
        token:'MINTME',
    },
    'E745':{
        web3:['https://host-154-14-192-66.contentfabric.io/eth'],
        token:'ELV',
    },
    'E755':{
        web3:['https://rpc.ethoprotocol.com'],
        token:'ETHO',
    },
    'E765':{
        web3:['https://mainnet-rpc.oneledger.network'],
        token:'OLT',
    },
    'E775':{
        web3:['https://mainnet.hashio.io/api'],
        token:'HBARE',
    },
    'E785':{
        web3:['https://json-rpc.evm.iotaledger.net'],
        token:'IOTAE',
    },
    'E795':{
        web3:['https://public-en.node.kaia.io'],
        token:'KAIA',
    },
    'E805':{
        web3:['https://rpc.soniclabs.com'],
        token:'S',
    },
    'E815':{
        web3:['https://mainnet-rpc.thundercore.io'],
        token:'TT',
    },
    'E835':{
        web3:['https://rpc.hyperliquid.xyz/evm'],
        token:'HYPE',
    },
    'E845':{
        web3:['https://rpc.xrplevm.org'],
        token:'XRPE',
    },
    'E855':{
        web3:['https://api.mainnet.abs.xyz'],
        token:'ABETH',
    },
    'E865':{
        web3:['https://apechain.drpc.org'],
        token:'APE',
    },
    'E875':{
        web3:['https://rpc.bitlayer.org'],
        token:'BIBTC',
    },
    'E885':{
        web3:['https://rpc.blast.io'],
        token:'BLETH',
    },
    'E895':{
        web3:['https://rpc.gobob.xyz/'],
        token:'BOETH',
    },
    'E905':{
        web3:['https://rpc.botanixlabs.com'],
        token:'BOBTC',
    },
    'E915':{
        web3:['https://rpc.bsquared.network'],
        token:'BSBTC',
    },
    'E925':{
        web3:['https://core.drpc.org', 'https://rpc.coredao.org'],
        token:'CORE',
    },
    'E945':{
        web3:['https://node.mainnet.etherlink.com'],
        token:'XTZE',
    },
    'E955':{
        web3:['https://rpc.frax.com'],
        token:'FRAX',
    },
    'E965':{
        web3:['https://mainnet.hsk.xyz'],
        token:'HSK',
    },
    'E975':{
        web3:['https://rpc.hemi.network/rpc'],
        token:'HETH',
    },
    'E985':{
        web3:['https://rpc-qnd.inkonchain.com'],
        token:'IETH',
    },
    'E995':{
        web3:['https://rpc.lens.xyz'],
        token:'GHO',
    },
    'E1005':{
        web3:['https://rpc.linea.build '],
        token:'LETH',
    },
    'E1015':{
        web3:['https://rpc.api.lisk.com'],
        token:'LIETH',
    },
    'E1025':{
        web3:['https://merlin.drpc.org'],
        token:'MBTC',
    },
    'E1035':{
        web3:['https://rpc.metall2.com'],
        token:'METH',
    },
    'E1045':{
        web3:['https://metis-rpc.publicnode.com'],
        token:'METIS',
    },
    'E1055':{
        web3:['https://rpc-mainnet.mindnetwork.xyz'],
        token:'MIETH',
    },
    'E1075':{
        web3:['https://mainnet.mode.network/'],
        token:'MOETH',
    },
    'E1085':{
        web3:['https://mainnet-1.rpc.banelabs.org', 'https://mainnet-2.rpc.banelabs.org', 'https://mainnet-3.rpc.banelabs.org'],
        token:'GAS',
    },
    'E1095':{
        web3:['https://opbnb-rpc.publicnode.com'],
        token:'OBNB',
    },
    'E1105':{
        web3:['https://rpc.plume.org'],
        token:'PLUME',
    },
    'E1115':{
        web3:['https://rpc.katana.network/'],
        token:'KETH',
    },
    'E1135':{
        web3:['https://api.roninchain.com/rpc'],
        token:'RON',
    },
    'E1145':{
        web3:['https://scroll-rpc.publicnode.com'],
        token:'SETH',
    },
    'E1165':{
        web3:['https://rpc.soneium.org/'],
        token:'SONETH',
    },
    'E1175':{
        web3:['https://mainnet.superseed.xyz'],
        token:'SUETH',
    },
    'E1185':{
        web3:['https://rpc.taiko.xyz'],
        token:'TETH',
    },
    'E1205':{
        web3:['https://unichain-rpc.publicnode.com'],
        token:'UETH',
    },
    'E1215':{
        web3:['https://worldchain-mainnet.g.alchemy.com/public'],
        token:'WOETH',
    },
    'E1225':{
        web3:['https://rpc.xlayer.tech'],
        token:'OKB',
    },
    'E1245':{
        web3:['https://mainnet.zircuit.com'],
        token:'ZETH',
    },
    'E1255':{
        web3:['https://mainnet.era.zksync.io'],
        token:'ZKETH',
    },
    'E1265':{
        web3:['https://mainnet.zkevm.cronos.org/'],
        token:'zkCRO',
    },
    'E1275':{
        web3:['https://rpc.zerion.io/v1/zero'],
        token:'ZERETH',
    },
    'E1285':{
        web3:['https://rpc.sophon.xyz'],
        token:'SOPH',
    },
    'E1295':{
        web3:['https://pacific-rpc.manta.network/http'],
        token:'MAETH',
    },
    'E1305':{
        web3:['https://api.node.glif.io'],
        token:'FILE',
    },
    'E1315':{
        web3:['https://rpc3.monad.xyz', 'https://rpc1.monad.xyz', 'https://monad-mainnet.drpc.org'],
        token:'MON',
    },
    'E1325':{
        web3:['https://zora.drpc.org'],
        token:'ZOETH',
    },
    'E1335':{
        web3:['https://arbitrum-nova-rpc.publicnode.com', 'https://nova.arbitrum.io/rpc'],
        token:'ANETH',
    },
    'E1365':{
        web3:['https://rpc.immutable.com'],
        token:'IMX',
    },
    'E1375':{
        web3:['https://rpc.gokite.ai/', 'https://rpc-virginia.gokite.ai', 'https://rpc-tokyo.gokite.ai', 'https://rpc-ireland.gokite.ai'],
        token:'KITE',
    },
    'E1385':{
        web3:['https://sentry.evm-rpc.injective.network', 'https://injectiveevm-rpc.polkachu.com'],
        token:'INJE',
    }
}

module.exports = e5s;